### ISSUE TITLE
Result depends on order of charge moves

### ISSUE THREAD

**Issue by SimonTouchtech** [ymenghank/GoBattleSim#10]
Given default settings for PVP and the following input:

```
name,fmove,cmove,cmove2,cp,strategy2
Dragonair,Dragon Breath,Aqua Tail,Wrap,1500,1
Lucario,Counter,Power-up Punch,Flash Cannon,1500,1
```

I get the following result:

```
0	-0.44545454545454543
0.44545454545454543	0
```

If I switch positioning between Power-up Punch and Flash Cannon for Lucario I get a different result, i.e. 

```
name,fmove,cmove,cmove2,cp,strategy2
Dragonair,Dragon Breath,Aqua Tail,Wrap,1500,1
Lucario,Counter,Flash Cannon,Power-up Punch,1500,1
```

gives me 

```
0	0.048387096774193505
-0.048387096774193505	0
```

I tried this in both Chrome (73.0.3683.86) and Edge (42.17134.1.0) on Windows 10 (10.0.17134.590) with the same results for both. I also tried the same thing with Shadow Ball instead of Flash Cannon and then the results were the same (+/-0.048...) regardless of order.

**Comment by ymenghank** [comment]
Hi, thanks for pointing out the issue! Has been fixed in 3.7.2

The old PvP strategy gives priority to the primary charge move (the move with highest DPS, which is Flash Cannon in the case). If the first cmove is Flash Cannon, it will be chosen immediately despite the other cmove (Power-up Punch) could KO the enemy (if unshield'd) with less energy.

Really hard to find this bug!
